apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  ports:
    - name: cql
      port: 9042
    - name: thrift
      port: 9160
  selector:
    app: cassandra
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cassandra
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: pmdcosta/cassandra:latest
          resources:
            requests:
              memory: "400Mi"
          ports:
            - containerPort: 9042
            - containerPort: 9160
          env:
            - name: MAX_HEAP_SIZE
              value: 300M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /cassandra_data/
              name: data
      volumes:
        - name: data
          emptyDir: {}

